version: 2
jobs:
  build:
    working_directory: ~/circle-test
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'npm install npm@latest'
      - run:
          name: list-versions
          command: 'npm --v && node -v'
      - run:
          name: install-depencencies
          command: cd ./usr/template/ && npm install && ls -la ./node_modules/
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              - git config --global user.email "circle@example.com"
              - git config --global user.name "CircleCI"
              - git add . ./usr/template/node_modules/
              - git commit -m 'update node_modules'
              - git push -u origin release
            fi