version: 2
jobs:
  build:
    working_directory: ~/circle-test
    docker:
      - image: circleci/node:8.1.0
    steps:
      - checkout
      - run:
          name: list-versions
          command: 'npm --v && node -v'
      - run:
          name: install-depencencies
          command: cd ./usr/template/ && ls -la && npm install
