version: 2
jobs:
  build:
    working_directory: ~/circle-test
    docker:
      - image: circleci/node:6.9
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: list-versions
          command: 'npm --v && node -v'
      - run:
          name: install-depencencies
          command: cd ./usr/template/ && ls -la && npm install
