version: 2
jobs:
  build:
    working_directory: ~/circle-test
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'RUN curl -sL https://deb.nodesource.com/setup_6.9.0 | bash - && \
                    	apt-get update && apt-get install -y nodejs && \
                    	npm install npm@latest -g'
      - run:
          name: list-versions
          command: 'npm --v && node -v'
      - run:
          name: install-depencencies
          command: cd ./usr/template/ && ls -la && npm install
